### ISSUE TITLE
Build times for the docs site are really slow compared to every other faithfulpack.net site

### ISSUE THREAD

**Issue by 3vorp** [Faithful-Resource-Pack/Docs#14]
## Problem

When making changes to the docs site, the time from commit to finishing building takes several minutes. The main site and the webapp take around a minute if not less.

## Expected Outcome

The site takes around a minute to build, similar to all the other https://faithfulpack.net based sites.

## Notes

Pretty sure Robert said the issue is that the docs site compile all the images again on every commit unnecessarily, increasing build times.

Also not really a high priority change, just a nice quality of life addition that would make changes a lot easier to push.

**Comment by TheRolfFR** [comment]
It looks like vite transform takes most of the 4 minutes:
https://github.com/Faithful-Resource-Pack/Docs/actions/runs/3258719874/jobs/5351015134#step:8:19

This step is responsible for transforming markdown, script, creating images thumbnails, so no I don't think it can be sped up.
Image thumbnail would need some sort of caching, and I added more verbose into log in order to check timestamp, but not an easy task to do.

**Comment by RobertRR11** [comment]
> so no I don't think it can be sped up

It definitely can be sped up, because right now it's always being built on github actions, meaning it's built again every commit, instead changing it to build on the server like every other project we have, it would only rebuild what's needed and speed up build time

**Comment by 3vorp** [comment]
yeah I wouldn't have even noticed a problem but literally every other site builds in like 1/4 the time

**Comment by RobertRR11** [comment]
fixed in 88704ed build time on average will now be 30 seconds.

**Comment by 3vorp** [comment]
épico
